### ISSUE TITLE
beta-phylogenetic-alt: psutil(logical=False) reports too few CPUs on EC2

### ISSUE THREAD

**Issue by wasade** [qiime2/q2-diversity-lib#25]
**Current Behavior**
The current CPU count check uses `logical=False` which has the effect of returning the number of "physical" cores observed on the system. For EC2, this is seen as only a single core. I believe the original intent of this was to discourage use of hyperthreading -- performance testing had suggested hyperthreading to be detrimental relative to avoiding it however using multiple threads is still faster than using a single thread.

**Proposed Behavior**
The suggested fix here is to set `logical=True`. In addition, we may want to update the error to a warning, and to warn if the number of requested threads is > 16. The motivation for 16 is that's where performance leveled out when testing on 32-core boxes.  

**References**
As reported on the QIIME 2 forum [here](https://forum.qiime2.org/t/beta-phylogenetic-alt-errors-when-run-in-parallel/4869/4), and the code presenting an issue is [here](https://github.com/qiime2/q2-diversity/blob/119b492bae4a6924ee2c85e9d2a172b9386c5b0a/q2_diversity/_beta/_method.py#L97).

**Comment by ChrisKeefe** [comment]
@thermokarst, we're still using `logical=False`; are you sure we want to close this? 

In addition to the performance issue @wasade describes here, psutil's `cpu_count(logical=False)` is apparently buggy on [multi-socket systems](https://github.com/giampaolo/psutil/issues/1558) and at least some [Docker containers](https://github.com/giampaolo/psutil/issues/1783). These issues might be resolved soon, but it's been a couple months and nothing's been merged yet. 

Going to `logical=True` might be a win, and adding a "lots of cpus" warning in [`validate_requested_cpus`](https://github.com/qiime2/q2-diversity-lib/blob/6357399c95a2fdd0dd9d9d95ba88f3b366fe8082/q2_diversity_lib/_util.py#L53) should be straightforward.

**Comment by thermokarst** [comment]
I think closing the issue makes sense: the [first-line `cpu_affinity` check](https://github.com/qiime2/q2-diversity-lib/blob/6357399c95a2fdd0dd9d9d95ba88f3b366fe8082/q2_diversity_lib/_util.py#L75) gets us 99% of the way there, so the `cpu_count(logical=False)` business is really just a fallback in case `cpu_affinity` isn't available on a host (which I think is just on darwin systems). I also just checked this `cpu_affinity` logic out in a few EC2 instances, and all report back the right number of cores.
