### ISSUE TITLE
Allow Bray-Curtis to accept Relative Frequency Data

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-diversity-lib#27]
**Improvement Description**
Allow FeatureTable[RelativeFrequency] to be passed to `bray_curtis` ([1](https://github.com/qiime2/q2-diversity-lib/blob/6357399c95a2fdd0dd9d9d95ba88f3b366fe8082/q2_diversity_lib/plugin_setup.py#L140), [2](https://github.com/qiime2/q2-diversity-lib/blob/6357399c95a2fdd0dd9d9d95ba88f3b366fe8082/q2_diversity_lib/beta.py#L123))

**Current Behavior**
Only FeatureTable[Frequency] is allowed.

**Comments**
IIRC, I ran into some unexpected test failures when initially trying to implement this. Tests showing that Bray-Curtis produces expected results with relative frequency data will be required in any PR that closes this issue.

**Comment by cherman2** [comment]
addressing in #60
