### ISSUE TITLE
add unit tests of scipy-based qualitative alpha and beta diversity metrics 

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity-lib#4]
**Improvement Description**
To confirm that feature tables are converted to presence/absence data before the metric is applied (sklearn handles this for a lot of methods, so we need tests to ensure that we know if that ever changes). 

**References**
See https://github.com/qiime2/q2-diversity/issues/189 for more context.

**Comment by cherman2** [comment]
I am going to close this because it doesn't seem to have traction. Please re-open if you disagree
